In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ds-dataset/sensitive_dev.json
/kaggle/input/ds-dataset/sensitive_train.json
/kaggle/input/ds-dataset/sensitive_test.json


In [2]:
import pprint

from sklearn import preprocessing, metrics
import torch
import torchtext
import torchtext.transforms as T
# from torch.hub import load_state_dict_from_url
from torch.utils.data import DataLoader

import pickle

In [3]:
train_df = pd.read_json('/kaggle/input/ds-dataset/sensitive_train.json')
train_df

text      label
0     Mayorga said that ahead of El Salvador’s legis...   politics
1     Citing unnamed sources, The Associated Press r...   politics
2     Instead, she said, Bukele came to meet with th...   politics
3     Mayorga said Bukele’s government didn’t say an...   politics
4     Animosity between the two appears to have star...   politics
...                                                 ...        ...
1527  Why do mass casualty attackers Livestream thei...  terrorism
1528  Paris Attacks Trial Resumes With Main Suspect ...  terrorism
1529  4 Burkina Troops, 3 Civilians Killed in Jihadi...  terrorism
1530  Why is ISIS recruiting beyond countries in phy...  terrorism
1531  UN to investigate prison attack that killed do...  terrorism

[1532 rows x 2 columns]

In [4]:
train_df['label'].unique()

array(['politics', 'religion', 'terrorism', 'neutral', 'insult'],
      dtype=object)

In [5]:
label_encoder = preprocessing.LabelEncoder()
train_df['label'] = label_encoder.fit_transform(train_df['label'])
train_df

text  label
0     Mayorga said that ahead of El Salvador’s legis...      2
1     Citing unnamed sources, The Associated Press r...      2
2     Instead, she said, Bukele came to meet with th...      2
3     Mayorga said Bukele’s government didn’t say an...      2
4     Animosity between the two appears to have star...      2
...                                                 ...    ...
1527  Why do mass casualty attackers Livestream thei...      4
1528  Paris Attacks Trial Resumes With Main Suspect ...      4
1529  4 Burkina Troops, 3 Civilians Killed in Jihadi...      4
1530  Why is ISIS recruiting beyond countries in phy...      4
1531  UN to investigate prison attack that killed do...      4

[1532 rows x 2 columns]

In [6]:
train_df['label'].unique()

array([2, 3, 4, 1, 0])

In [7]:
test_df = pd.read_json('/kaggle/input/ds-dataset/sensitive_test.json')
test_df

text     label
0     ET, saying that the GOP failed to show that an...  politics
1     Despite potential safety concerns, Gates has b...  politics
2     The word cheating also trended on Twitter on t...  politics
3     The worker is seen telling voters to place the...  politics
4     Both Lake and Ward have espoused baseless clai...  politics
...                                                 ...       ...
1014  After MEPs passed a scathing Russian resolutio...  politics
1015  Kim Jong Un 'Seriously Ill' In North Korea Cov...  politics
1016  Israeli rules say West Bank visitors must decl...  politics
1017  Ethiopia Deploys New Troops into Neighboring S...  politics
1018  Cyberattack on Albanian government suggests ne...  politics

[1019 rows x 2 columns]

In [8]:
test_df['label'].unique()

array(['politics', 'neutral', 'insult', 'religion', 'terrorism'],
      dtype=object)

In [9]:
test_df['label'] = label_encoder.transform(test_df['label'])
test_df

text  label
0     ET, saying that the GOP failed to show that an...      2
1     Despite potential safety concerns, Gates has b...      2
2     The word cheating also trended on Twitter on t...      2
3     The worker is seen telling voters to place the...      2
4     Both Lake and Ward have espoused baseless clai...      2
...                                                 ...    ...
1014  After MEPs passed a scathing Russian resolutio...      2
1015  Kim Jong Un 'Seriously Ill' In North Korea Cov...      2
1016  Israeli rules say West Bank visitors must decl...      2
1017  Ethiopia Deploys New Troops into Neighboring S...      2
1018  Cyberattack on Albanian government suggests ne...      2

[1019 rows x 2 columns]

In [10]:
test_df['label'].unique()

array([2, 1, 0, 3, 4])

In [11]:
# https://pytorch.org/text/main/transforms.html#padtransform
from torch import Tensor

class PadTransform(torch.nn.Module):
    """Pad tensor to a fixed length with given padding value.

    :param max_length: Maximum length to pad to
    :type max_length: int
    :param pad_value: Value to pad the tensor with
    :type pad_value: bool
    """

    def __init__(self, max_length: int, pad_value: int) -> None:
        super().__init__()
        self.max_length = max_length
        self.pad_value = float(pad_value)
        
    def forward(self, x: Tensor) -> Tensor:
        """
        :param x: The tensor to pad
        :type x: Tensor
        :return: Tensor padded up to max_length with pad_value
        :rtype: Tensor
        """
        max_encoded_length = x.size(-1)
        if max_encoded_length < self.max_length:
            pad_amount = self.max_length - max_encoded_length
            x = torch.nn.functional.pad(x, (0, pad_amount), value=self.pad_value)
        return x

In [12]:
padding_idx = 1
bos_idx = 0
eos_idx = 2
max_seq_len = 256

In [13]:
# https://pytorch.org/text/main/tutorials/sst2_classification_non_distributed.html#
text_transform = torchtext.models.XLMR_LARGE_ENCODER.transform()

100%|██████████| 5.07M/5.07M [00:00<00:00, 5.20MB/s]
Downloading: "https://download.pytorch.org/models/text/xlmr.vocab.pt" to /root/.cache/torch/hub/checkpoints/xlmr.vocab.pt


  0%|          | 0.00/4.85M [00:00<?, ?B/s]

In [14]:
print(train_df.iloc[0, 0])
text_transform(train_df.iloc[0, 0])

Mayorga said that ahead of El Salvador’s legislative elections, Torres spread false information by saying Bukele had come to Washington to meet with administration officials


[0,
 104610,
 208,
 2804,
 450,
 99255,
 111,
 540,
 61356,
 26,
 7,
 62289,
 13,
 81843,
 7,
 4,
 113984,
 93403,
 98320,
 4677,
 390,
 54433,
 667,
 49713,
 1902,
 1380,
 47,
 17955,
 47,
 23356,
 678,
 86052,
 51521,
 7,
 2]

In [15]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.df = df
    
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        return (
            # PadTransform(max_length=256, pad_value=padding_idx)(torch.tensor(text_transform(self.df.iloc[idx, 0]))),
            torch.tensor(text_transform(self.df.iloc[idx, 0])),
            torch.nn.functional.one_hot(torch.tensor(self.df.iloc[idx, 1]), 5)
            # torch.tensor(self.df.iloc[idx, 1])
        )

In [16]:
train_dataset = CustomDataset(train_df)
# pprint.pprint(next(iter(train_dataset)))

In [17]:
test_dataset = CustomDataset(test_df)
# pprint.pprint(next(iter(test_dataset)))

In [18]:
# https://stackoverflow.com/questions/35050753/how-big-should-batch-size-and-number-of-epochs-be-when-fitting-a-model#:~:text=Generally%20batch%20size%20of%2032,b%2Fw%2050%20to%20100.
# https://stackoverflow.com/questions/68479235/cuda-out-of-memory-error-cannot-reduce-batch-size
SMALL_BATCH_SIZE = 16
K = 2
LARGE_BATCH_SIZE = K * SMALL_BATCH_SIZE

In [19]:
import torchtext.functional as F

def batch_collate_fn(batch):
    inp_list = list()
    tar_list = list()
    
    for sample in batch:
        inp_list.append(sample[0].tolist())
        tar_list.append(sample[1])
        
    padded_tensor = F.to_tensor(inp_list, padding_value=padding_idx)
    target_tensor = torch.stack(tar_list).double()
    
    return padded_tensor, target_tensor

In [20]:
train_dataloader = DataLoader(
    dataset=train_dataset,
    batch_size=SMALL_BATCH_SIZE,
    shuffle=True,
    collate_fn=batch_collate_fn
)

In [21]:
test_dataloader = DataLoader(
    dataset=test_dataset,
    batch_size=SMALL_BATCH_SIZE,
    shuffle=False,
    collate_fn=batch_collate_fn
)

In [22]:
# next(iter(train_dataloader)) 

In [23]:
num_classes = 5
input_dim = 768

from torchtext.models import RobertaClassificationHead, XLMR_BASE_ENCODER

classifier_head = RobertaClassificationHead(num_classes=num_classes, input_dim=input_dim)
model = XLMR_BASE_ENCODER.get_model(head=classifier_head)

Downloading: "https://download.pytorch.org/models/text/xlmr.base.encoder.pt" to /root/.cache/torch/hub/checkpoints/xlmr.base.encoder.pt


  0%|          | 0.00/1.03G [00:00<?, ?B/s]

In [24]:
DEVICE = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
DEVICE

device(type='cuda')

In [25]:
model.to(DEVICE)

RobertaModel(
  (encoder): RobertaEncoder(
    (transformer): TransformerEncoder(
      (token_embedding): Embedding(250002, 768, padding_idx=1)
      (layers): ModuleList(
        (0): TransformerEncoderLayer(
          (dropout): Dropout(p=0.1, inplace=False)
          (attention): MultiheadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (input_projection): Linear(in_features=768, out_features=2304, bias=True)
            (output_projection): Linear(in_features=768, out_features=768, bias=True)
          )
          (residual_mlp): ResidualMLP(
            (mlp): Sequential(
              (0): Linear(in_features=768, out_features=3072, bias=True)
              (1): GELU()
              (2): Dropout(p=0.1, inplace=False)
              (3): Linear(in_features=3072, out_features=768, bias=True)
              (4): Dropout(p=0.1, inplace=False)
            )
          )
          (attention_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)


In [26]:
import torchtext.functional as F
from torch.optim import AdamW

learning_rate = 1.4e-5  # 1e-5  
optim = AdamW(model.parameters(), lr=learning_rate)

# e-3 = default is really bad (predict only one class) ,
# e-7 is too slow, e-6 is too slow
# e-5 by far has the fastest converges, but not consistently there
# 3e-6 isnt good
# 5e-6 converges slower but also good (might be better than e-5 ?)
# 6e-6 is good
# 7e-6 is good (consistently ~0.75 acc, reached ~0.76 acc)
# 8e-6 is nearly the best (more consistent ~0.75 acc, reached ~0.76 acc)
# 9e-6 is nearly the best
# 1.1e-5 is good
# 1.2e-5 is the best
# 1.3e-5 testing
# 1.4e-5 testing

criteria = torch.nn.CrossEntropyLoss()


def train_step(input, target, small_batch_no):
    output = model(input)
    loss = criteria(output, target)
    loss.backward()
    
    if (small_batch_no + 1) % K == 0 or (small_batch_no + 1) == len(train_dataloader):
        optim.step()
        optim.zero_grad()


def evaluate():
    model.eval()
    
    total_loss = 0
    counter = 0
    
    with torch.no_grad():
        # for batch in dev_dataloader:
        for i, batch in enumerate(test_dataloader):
            input = batch[0].clone().detach().to(DEVICE)
            output = model(input)
            target = batch[1].clone().detach().to(DEVICE)
            
            if i == 0:
                class_output = torch.argmax(output, dim=1)
                class_target = torch.argmax(target, dim=1)
            else:
                class_output = torch.cat([class_output, torch.argmax(output, dim=1)])
                class_target = torch.cat([class_target, torch.argmax(target, dim=1)])
            
            # loss, predictions, step_confusion_matrix = eval_step(input, target)
            # loss = eval_step(input, target)
            loss = criteria(output, target).item()
            
            total_loss += loss
            # correct_predictions += predictions
            # total_predictions += len(target)
            counter += 1
            
            
        confusion_matrix = metrics.confusion_matrix(
            class_target.cpu().numpy().flatten(),
            class_output.cpu().numpy().flatten(),
            labels=[0, 1, 2, 3, 4]
        ) 
        classification_report = metrics.classification_report(
            class_target.cpu().numpy().flatten(),
            class_output.cpu().numpy().flatten(),
            labels=[0, 1, 2, 3, 4],
            output_dict=True
        )
            
    

    return (
        total_loss,
        counter,
        confusion_matrix,
        classification_report
    )



In [27]:
num_epochs = 50

In [28]:
def log_epoch(epoch, **kwargs):
    with open(f'log_epoch_{epoch}.pkl', 'wb') as f:
        pickle.dump(kwargs, f)
    
    # the model is really heavy (1.11GB)
    # so only save each 5-th one and the last one
    if epoch % 5 == 0 or epoch == num_epochs - 1:
        torch.save(model.state_dict(), f'model_epoch_{epoch}.pth')

In [29]:
for e in range(num_epochs):
    # wonder if i need this or not
    model.train()
    
    for small_batch_no, small_batch in enumerate(train_dataloader):
        # input = F.to_tensor(batch["token_ids"], padding_value=padding_idx).to(DEVICE)
        # target = torch.tensor(batch["target"]).to(DEVICE)
        # input = F.to_tensor(batch[0], padding_value=padding_idx).to(DEVICE)
        input = small_batch[0].clone().detach().to(DEVICE)
        target = small_batch[1].clone().detach().to(DEVICE)
        train_step(input, target, small_batch_no)
        
        torch.cuda.empty_cache()

    total_loss, counter, confusion_matrix, classification_report = evaluate()
    # loss = evaluate()
    print(f'EPOCH {e}')
    print(f'total_loss={total_loss}')
    print(f'counter={counter}')
    print(f'loss=total_loss/counter={total_loss/counter}')
    print(f'confusion_matrix=\n{confusion_matrix}')
    
    print('classification_report=')
    pprint.pprint(classification_report)
    
    log_epoch(
        e,
        total_loss=total_loss,
        counter=counter,
        loss=total_loss/counter,
        confusion_matrix=confusion_matrix,
        classification_report=classification_report
    )
    # print("loss = [{}], \nconfusion_matrix = [{}], \nclassification_report = [{}]"\
    #      .format(loss, confusion_matrix, classification_report))
    

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/skle

EPOCH 0
total_loss=91.27679351073775
counter=64
loss=total_loss/counter=1.4261998986052773
confusion_matrix=
[[ 56 129   0   0  20]
 [  0 153   0   0 117]
 [  0   8   0   0 166]
 [  0 121   0   0  38]
 [  0   3   0   0 208]]
classification_report=
{'0': {'f1-score': 0.42911877394636017,
       'precision': 1.0,
       'recall': 0.2731707317073171,
       'support': 205},
 '1': {'f1-score': 0.4473684210526315,
       'precision': 0.3695652173913043,
       'recall': 0.5666666666666667,
       'support': 270},
 '2': {'f1-score': 0.0, 'precision': 0.0, 'recall': 0.0, 'support': 174},
 '3': {'f1-score': 0.0, 'precision': 0.0, 'recall': 0.0, 'support': 159},
 '4': {'f1-score': 0.5473684210526315,
       'precision': 0.3788706739526412,
       'recall': 0.985781990521327,
       'support': 211},
 'accuracy': 0.40922473012757604,
 'macro avg': {'f1-score': 0.2847711232103246,
               'precision': 0.3496871782687891,
               'recall': 0.36512387777906213,
               'support'

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 1
total_loss=70.64861022240736
counter=64
loss=total_loss/counter=1.103884534725115
confusion_matrix=
[[102  79   2   4  18]
 [  1 150  38   4  77]
 [  0   4  65   0 105]
 [  0  66   0  82  11]
 [  0   3   0   0 208]]
classification_report=
{'0': {'f1-score': 0.6623376623376623,
       'precision': 0.9902912621359223,
       'recall': 0.4975609756097561,
       'support': 205},
 '1': {'f1-score': 0.5244755244755246,
       'precision': 0.4966887417218543,
       'recall': 0.5555555555555556,
       'support': 270},
 '2': {'f1-score': 0.4659498207885304,
       'precision': 0.6190476190476191,
       'recall': 0.3735632183908046,
       'support': 174},
 '3': {'f1-score': 0.6586345381526104,
       'precision': 0.9111111111111111,
       'recall': 0.5157232704402516,
       'support': 159},
 '4': {'f1-score': 0.6603174603174603,
       'precision': 0.4964200477326969,
       'recall': 0.985781990521327,
       'support': 211},
 'accuracy': 0.5956820412168793,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 2
total_loss=61.505137303685345
counter=64
loss=total_loss/counter=0.9610177703700835
confusion_matrix=
[[147  38  11   3   6]
 [  0 112 104  28  26]
 [  0   3 106   2  63]
 [  0  15   0 138   6]
 [  0   2   3   0 206]]
classification_report=
{'0': {'f1-score': 0.8352272727272727,
       'precision': 1.0,
       'recall': 0.7170731707317073,
       'support': 205},
 '1': {'f1-score': 0.509090909090909,
       'precision': 0.6588235294117647,
       'recall': 0.4148148148148148,
       'support': 270},
 '2': {'f1-score': 0.5326633165829145,
       'precision': 0.4732142857142857,
       'recall': 0.6091954022988506,
       'support': 174},
 '3': {'f1-score': 0.8363636363636363,
       'precision': 0.8070175438596491,
       'recall': 0.8679245283018868,
       'support': 159},
 '4': {'f1-score': 0.7953667953667953,
       'precision': 0.6710097719869706,
       'recall': 0.976303317535545,
       'support': 211},
 'accuracy': 0.6957801766437685,
 'macro avg': {'f1-score': 0.701742

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 3
total_loss=56.83890467023329
counter=64
loss=total_loss/counter=0.8881078854723952
confusion_matrix=
[[145  53   4   3   0]
 [  2 135  95  28  10]
 [  0   6 125   3  40]
 [  0  17   0 141   1]
 [  0   2  12   2 195]]
classification_report=
{'0': {'f1-score': 0.8238636363636364,
       'precision': 0.9863945578231292,
       'recall': 0.7073170731707317,
       'support': 205},
 '1': {'f1-score': 0.5590062111801243,
       'precision': 0.6338028169014085,
       'recall': 0.5,
       'support': 270},
 '2': {'f1-score': 0.6097560975609756,
       'precision': 0.5296610169491526,
       'recall': 0.7183908045977011,
       'support': 174},
 '3': {'f1-score': 0.8392857142857143,
       'precision': 0.7966101694915254,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8533916849015318,
       'precision': 0.7926829268292683,
       'recall': 0.9241706161137441,
       'support': 211},
 'accuracy': 0.7271835132482827,
 'macro avg': {'f1-score': 0.73706

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 4
total_loss=56.84087879830358
counter=64
loss=total_loss/counter=0.8881387312234934
confusion_matrix=
[[169  30   1   5   0]
 [  2 155  80  21  12]
 [  0   9 111   4  50]
 [  0  17   0 141   1]
 [  0   1   4   2 204]]
classification_report=
{'0': {'f1-score': 0.898936170212766,
       'precision': 0.9883040935672515,
       'recall': 0.824390243902439,
       'support': 205},
 '1': {'f1-score': 0.6431535269709543,
       'precision': 0.7311320754716981,
       'recall': 0.5740740740740741,
       'support': 270},
 '2': {'f1-score': 0.6,
       'precision': 0.5663265306122449,
       'recall': 0.6379310344827587,
       'support': 174},
 '3': {'f1-score': 0.8493975903614457,
       'precision': 0.815028901734104,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8535564853556487,
       'precision': 0.7640449438202247,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7654563297350343,
 'macro avg': {'f1-score': 0.769008754

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 5
total_loss=74.60198038518006
counter=64
loss=total_loss/counter=1.1656559435184384
confusion_matrix=
[[171  22   4   4   4]
 [  2  91 112  40  25]
 [  0   3 114   2  55]
 [  0  13   0 144   2]
 [  0   0   4   1 206]]
classification_report=
{'0': {'f1-score': 0.9047619047619047,
       'precision': 0.9884393063583815,
       'recall': 0.8341463414634146,
       'support': 205},
 '1': {'f1-score': 0.456140350877193,
       'precision': 0.7054263565891473,
       'recall': 0.337037037037037,
       'support': 270},
 '2': {'f1-score': 0.5588235294117647,
       'precision': 0.48717948717948717,
       'recall': 0.6551724137931034,
       'support': 174},
 '3': {'f1-score': 0.8228571428571428,
       'precision': 0.7539267015706806,
       'recall': 0.9056603773584906,
       'support': 159},
 '4': {'f1-score': 0.8190854870775348,
       'precision': 0.7054794520547946,
       'recall': 0.976303317535545,
       'support': 211},
 'accuracy': 0.7124631992149166,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 6
total_loss=65.88347402226249
counter=64
loss=total_loss/counter=1.0294292815978514
confusion_matrix=
[[177  23   1   3   1]
 [  4 136  95  22  13]
 [  0   6 118   3  47]
 [  0  18   0 140   1]
 [  0   0   5   2 204]]
classification_report=
{'0': {'f1-score': 0.9170984455958548,
       'precision': 0.9779005524861878,
       'recall': 0.8634146341463415,
       'support': 205},
 '1': {'f1-score': 0.6004415011037527,
       'precision': 0.7431693989071039,
       'recall': 0.5037037037037037,
       'support': 270},
 '2': {'f1-score': 0.6005089058524172,
       'precision': 0.5388127853881278,
       'recall': 0.6781609195402298,
       'support': 174},
 '3': {'f1-score': 0.851063829787234,
       'precision': 0.8235294117647058,
       'recall': 0.8805031446540881,
       'support': 159},
 '4': {'f1-score': 0.8553459119496855,
       'precision': 0.7669172932330827,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.760549558390579,
 'macro avg': {'f1-sco

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 7
total_loss=72.81716136209434
counter=64
loss=total_loss/counter=1.137768146282724
confusion_matrix=
[[173  25   2   0   5]
 [  1 121 103  21  24]
 [  0   5 117   3  49]
 [  0  18   0 141   0]
 [  0   1   5   2 203]]
classification_report=
{'0': {'f1-score': 0.912928759894459,
       'precision': 0.9942528735632183,
       'recall': 0.8439024390243902,
       'support': 205},
 '1': {'f1-score': 0.55,
       'precision': 0.711764705882353,
       'recall': 0.44814814814814813,
       'support': 270},
 '2': {'f1-score': 0.5835411471321696,
       'precision': 0.5154185022026432,
       'recall': 0.6724137931034483,
       'support': 174},
 '3': {'f1-score': 0.8650306748466258,
       'precision': 0.844311377245509,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8252032520325204,
       'precision': 0.7224199288256228,
       'recall': 0.9620853080568721,
       'support': 211},
 'accuracy': 0.7409224730127576,
 'macro avg': {'f1-score': 0.7473407

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 8
total_loss=73.60208209213107
counter=64
loss=total_loss/counter=1.150032532689548
confusion_matrix=
[[178  22   0   2   3]
 [  2 123  95  25  25]
 [  0   5 111   3  55]
 [  0  16   0 143   0]
 [  0   1   2   2 206]]
classification_report=
{'0': {'f1-score': 0.9246753246753248,
       'precision': 0.9888888888888889,
       'recall': 0.8682926829268293,
       'support': 205},
 '1': {'f1-score': 0.562929061784897,
       'precision': 0.7365269461077845,
       'recall': 0.45555555555555555,
       'support': 270},
 '2': {'f1-score': 0.5811518324607331,
       'precision': 0.5336538461538461,
       'recall': 0.6379310344827587,
       'support': 174},
 '3': {'f1-score': 0.8562874251497006,
       'precision': 0.8171428571428572,
       'recall': 0.89937106918239,
       'support': 159},
 '4': {'f1-score': 0.8240000000000001,
       'precision': 0.71280276816609,
       'recall': 0.976303317535545,
       'support': 211},
 'accuracy': 0.746810598626104,
 'macro avg': {'f1-score':

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 9
total_loss=74.79660123760483
counter=64
loss=total_loss/counter=1.1686968943375755
confusion_matrix=
[[147  49   1   6   2]
 [  2 131  85  35  17]
 [  0   8 111   5  50]
 [  0  16   0 143   0]
 [  0   1   4   2 204]]
classification_report=
{'0': {'f1-score': 0.8305084745762712,
       'precision': 0.9865771812080537,
       'recall': 0.7170731707317073,
       'support': 205},
 '1': {'f1-score': 0.5515789473684211,
       'precision': 0.6390243902439025,
       'recall': 0.48518518518518516,
       'support': 270},
 '2': {'f1-score': 0.5920000000000001,
       'precision': 0.5522388059701493,
       'recall': 0.6379310344827587,
       'support': 174},
 '3': {'f1-score': 0.8171428571428571,
       'precision': 0.7486910994764397,
       'recall': 0.89937106918239,
       'support': 159},
 '4': {'f1-score': 0.8429752066115703,
       'precision': 0.7472527472527473,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7222767419038273,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 10
total_loss=82.84646012944458
counter=64
loss=total_loss/counter=1.2944759395225716
confusion_matrix=
[[175  24   2   2   2]
 [  0 107 116  31  16]
 [  0   6 123   1  44]
 [  0  17   0 142   0]
 [  0   0   8   2 201]]
classification_report=
{'0': {'f1-score': 0.9210526315789475,
       'precision': 1.0,
       'recall': 0.8536585365853658,
       'support': 205},
 '1': {'f1-score': 0.5047169811320754,
       'precision': 0.6948051948051948,
       'recall': 0.3962962962962963,
       'support': 270},
 '2': {'f1-score': 0.5815602836879433,
       'precision': 0.4939759036144578,
       'recall': 0.7068965517241379,
       'support': 174},
 '3': {'f1-score': 0.8427299703264095,
       'precision': 0.797752808988764,
       'recall': 0.8930817610062893,
       'support': 159},
 '4': {'f1-score': 0.8481012658227848,
       'precision': 0.7642585551330798,
       'recall': 0.95260663507109,
       'support': 211},
 'accuracy': 0.7340529931305201,
 'macro avg': {'f1-score': 0.7396322

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 11
total_loss=75.65114935121461
counter=64
loss=total_loss/counter=1.1820492086127283
confusion_matrix=
[[172  30   0   1   2]
 [  3 138  91  19  19]
 [  0   9 113   2  50]
 [  0  21   0 138   0]
 [  0   1   7   1 202]]
classification_report=
{'0': {'f1-score': 0.9052631578947368,
       'precision': 0.9828571428571429,
       'recall': 0.8390243902439024,
       'support': 205},
 '1': {'f1-score': 0.5884861407249466,
       'precision': 0.6934673366834171,
       'recall': 0.5111111111111111,
       'support': 270},
 '2': {'f1-score': 0.587012987012987,
       'precision': 0.5355450236966824,
       'recall': 0.6494252873563219,
       'support': 174},
 '3': {'f1-score': 0.8625,
       'precision': 0.8571428571428571,
       'recall': 0.8679245283018868,
       'support': 159},
 '4': {'f1-score': 0.834710743801653,
       'precision': 0.73992673992674,
       'recall': 0.957345971563981,
       'support': 211},
 'accuracy': 0.7487733071638861,
 'macro avg': {'f1-score': 0.755594

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 12
total_loss=86.3842016061932
counter=64
loss=total_loss/counter=1.3497531500967688
confusion_matrix=
[[183  18   0   0   4]
 [  2 119  98  21  30]
 [  0   3 107   1  63]
 [  0  21   0 136   2]
 [  0   1   2   1 207]]
classification_report=
{'0': {'f1-score': 0.9384615384615385,
       'precision': 0.9891891891891892,
       'recall': 0.8926829268292683,
       'support': 205},
 '1': {'f1-score': 0.550925925925926,
       'precision': 0.7345679012345679,
       'recall': 0.44074074074074077,
       'support': 270},
 '2': {'f1-score': 0.5616797900262467,
       'precision': 0.5169082125603864,
       'recall': 0.6149425287356322,
       'support': 174},
 '3': {'f1-score': 0.8553459119496856,
       'precision': 0.8553459119496856,
       'recall': 0.8553459119496856,
       'support': 159},
 '4': {'f1-score': 0.8007736943907157,
       'precision': 0.6764705882352942,
       'recall': 0.981042654028436,
       'support': 211},
 'accuracy': 0.7379784102060843,
 'macro avg': {'f1-s

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 13
total_loss=84.09822467033452
counter=64
loss=total_loss/counter=1.3140347604739768
confusion_matrix=
[[182  20   1   0   2]
 [  5 118 100  31  16]
 [  0   6 116   3  49]
 [  0  18   0 141   0]
 [  0   2   6   3 200]]
classification_report=
{'0': {'f1-score': 0.9285714285714286,
       'precision': 0.9732620320855615,
       'recall': 0.8878048780487805,
       'support': 205},
 '1': {'f1-score': 0.543778801843318,
       'precision': 0.7195121951219512,
       'recall': 0.43703703703703706,
       'support': 270},
 '2': {'f1-score': 0.5843828715365239,
       'precision': 0.5201793721973094,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8367952522255193,
       'precision': 0.7921348314606742,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8368200836820084,
       'precision': 0.7490636704119851,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7428851815505397,
 'macro avg': {'f1

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 14
total_loss=90.70474100207106
counter=64
loss=total_loss/counter=1.4172615781573603
confusion_matrix=
[[178  21   2   2   2]
 [  1 118 109  28  14]
 [  0   6 120   2  46]
 [  0  17   0 142   0]
 [  0   1   7   3 200]]
classification_report=
{'0': {'f1-score': 0.9270833333333334,
       'precision': 0.994413407821229,
       'recall': 0.8682926829268293,
       'support': 205},
 '1': {'f1-score': 0.5450346420323325,
       'precision': 0.7239263803680982,
       'recall': 0.43703703703703706,
       'support': 270},
 '2': {'f1-score': 0.5825242718446602,
       'precision': 0.5042016806722689,
       'recall': 0.6896551724137931,
       'support': 174},
 '3': {'f1-score': 0.8452380952380952,
       'precision': 0.8022598870056498,
       'recall': 0.8930817610062893,
       'support': 159},
 '4': {'f1-score': 0.8456659619450317,
       'precision': 0.7633587786259542,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7438665358194309,
 'macro avg': {'f1

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 15
total_loss=89.72916599798059
counter=64
loss=total_loss/counter=1.4020182187184467
confusion_matrix=
[[163  34   0   4   4]
 [  4 118  79  44  25]
 [  0   7 106   6  55]
 [  0  14   0 145   0]
 [  0   0   2   3 206]]
classification_report=
{'0': {'f1-score': 0.8763440860215055,
       'precision': 0.9760479041916168,
       'recall': 0.7951219512195122,
       'support': 205},
 '1': {'f1-score': 0.5327313769751693,
       'precision': 0.6820809248554913,
       'recall': 0.43703703703703706,
       'support': 270},
 '2': {'f1-score': 0.5872576177285319,
       'precision': 0.5668449197860963,
       'recall': 0.6091954022988506,
       'support': 174},
 '3': {'f1-score': 0.8033240997229917,
       'precision': 0.7178217821782178,
       'recall': 0.9119496855345912,
       'support': 159},
 '4': {'f1-score': 0.8223552894211577,
       'precision': 0.7103448275862069,
       'recall': 0.976303317535545,
       'support': 211},
 'accuracy': 0.7242394504416094,
 'macro avg': {'f1

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 16
total_loss=91.43207823450376
counter=64
loss=total_loss/counter=1.4286262224141213
confusion_matrix=
[[162  39   1   1   2]
 [  3 125  92  32  18]
 [  0   6 116   6  46]
 [  0  19   0 140   0]
 [  0   0   8   3 200]]
classification_report=
{'0': {'f1-score': 0.8756756756756757,
       'precision': 0.9818181818181818,
       'recall': 0.7902439024390244,
       'support': 205},
 '1': {'f1-score': 0.5446623093681917,
       'precision': 0.6613756613756614,
       'recall': 0.46296296296296297,
       'support': 270},
 '2': {'f1-score': 0.5933503836317136,
       'precision': 0.5345622119815668,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8211143695014663,
       'precision': 0.7692307692307693,
       'recall': 0.8805031446540881,
       'support': 159},
 '4': {'f1-score': 0.8385744234800838,
       'precision': 0.7518796992481203,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7291462217860648,
 'macro avg': {'f

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 17
total_loss=94.07551164854225
counter=64
loss=total_loss/counter=1.4699298695084726
confusion_matrix=
[[157  41   1   3   3]
 [  1 127  95  30  17]
 [  0   7 117   5  45]
 [  0  17   0 142   0]
 [  0   1   7   2 201]]
classification_report=
{'0': {'f1-score': 0.8650137741046832,
       'precision': 0.9936708860759493,
       'recall': 0.7658536585365854,
       'support': 205},
 '1': {'f1-score': 0.548596112311015,
       'precision': 0.6580310880829016,
       'recall': 0.4703703703703704,
       'support': 270},
 '2': {'f1-score': 0.5939086294416244,
       'precision': 0.5318181818181819,
       'recall': 0.6724137931034483,
       'support': 174},
 '3': {'f1-score': 0.8328445747800587,
       'precision': 0.7802197802197802,
       'recall': 0.8930817610062893,
       'support': 159},
 '4': {'f1-score': 0.8427672955974843,
       'precision': 0.7556390977443609,
       'recall': 0.95260663507109,
       'support': 211},
 'accuracy': 0.7301275760549558,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 18
total_loss=93.1676196976557
counter=64
loss=total_loss/counter=1.4557440577758702
confusion_matrix=
[[178  24   1   0   2]
 [  1 134  98  20  17]
 [  0   7 119   1  47]
 [  0  21   0 137   1]
 [  0   1   4   2 204]]
classification_report=
{'0': {'f1-score': 0.9270833333333334,
       'precision': 0.994413407821229,
       'recall': 0.8682926829268293,
       'support': 205},
 '1': {'f1-score': 0.5864332603938731,
       'precision': 0.7165775401069518,
       'recall': 0.4962962962962963,
       'support': 270},
 '2': {'f1-score': 0.601010101010101,
       'precision': 0.536036036036036,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8589341692789968,
       'precision': 0.85625,
       'recall': 0.8616352201257862,
       'support': 159},
 '4': {'f1-score': 0.8464730290456431,
       'precision': 0.7527675276752768,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7576054955839058,
 'macro avg': {'f1-score': 0.76398

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 19
total_loss=97.4189845357571
counter=64
loss=total_loss/counter=1.5221716333712048
confusion_matrix=
[[177  24   1   1   2]
 [  1 128  95  31  15]
 [  0   6 116   6  46]
 [  0  20   0 139   0]
 [  0   1   4   2 204]]
classification_report=
{'0': {'f1-score': 0.9242819843342036,
       'precision': 0.9943820224719101,
       'recall': 0.8634146341463415,
       'support': 205},
 '1': {'f1-score': 0.5701559020044544,
       'precision': 0.7150837988826816,
       'recall': 0.4740740740740741,
       'support': 270},
 '2': {'f1-score': 0.5948717948717949,
       'precision': 0.5370370370370371,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8224852071005917,
       'precision': 0.776536312849162,
       'recall': 0.8742138364779874,
       'support': 159},
 '4': {'f1-score': 0.8535564853556487,
       'precision': 0.7640449438202247,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7497546614327772,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 20
total_loss=102.58480706636759
counter=64
loss=total_loss/counter=1.6028876104119936
confusion_matrix=
[[180  20   2   1   2]
 [  1 114 109  25  21]
 [  0   5 122   1  46]
 [  0  18   0 141   0]
 [  0   0   5   2 204]]
classification_report=
{'0': {'f1-score': 0.9326424870466321,
       'precision': 0.994475138121547,
       'recall': 0.8780487804878049,
       'support': 205},
 '1': {'f1-score': 0.5339578454332553,
       'precision': 0.7261146496815286,
       'recall': 0.4222222222222222,
       'support': 270},
 '2': {'f1-score': 0.5922330097087377,
       'precision': 0.5126050420168067,
       'recall': 0.7011494252873564,
       'support': 174},
 '3': {'f1-score': 0.8571428571428571,
       'precision': 0.8294117647058824,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8429752066115703,
       'precision': 0.7472527472527473,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.746810598626104,
 'macro avg': {'f1-s

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 21
total_loss=93.03055114995169
counter=64
loss=total_loss/counter=1.4536023617179952
confusion_matrix=
[[153  50   0   1   1]
 [  1 151  85  23  10]
 [  0  13 116   2  43]
 [  0  22   0 137   0]
 [  0   3   6   2 200]]
classification_report=
{'0': {'f1-score': 0.8523676880222841,
       'precision': 0.9935064935064936,
       'recall': 0.7463414634146341,
       'support': 205},
 '1': {'f1-score': 0.593320235756385,
       'precision': 0.6317991631799164,
       'recall': 0.5592592592592592,
       'support': 270},
 '2': {'f1-score': 0.6089238845144356,
       'precision': 0.5603864734299517,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8456790123456791,
       'precision': 0.8303030303030303,
       'recall': 0.8616352201257862,
       'support': 159},
 '4': {'f1-score': 0.860215053763441,
       'precision': 0.7874015748031497,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7428851815505397,
 'macro avg': {'f1-s

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 22
total_loss=85.3710848800633
counter=64
loss=total_loss/counter=1.333923201250989
confusion_matrix=
[[178  24   1   1   1]
 [  6 160  72  19  13]
 [  1  13 111   3  46]
 [  0  28   0 131   0]
 [  0   0   5   2 204]]
classification_report=
{'0': {'f1-score': 0.9128205128205128,
       'precision': 0.9621621621621622,
       'recall': 0.8682926829268293,
       'support': 205},
 '1': {'f1-score': 0.6464646464646464,
       'precision': 0.7111111111111111,
       'recall': 0.5925925925925926,
       'support': 270},
 '2': {'f1-score': 0.6115702479338844,
       'precision': 0.5873015873015873,
       'recall': 0.6379310344827587,
       'support': 174},
 '3': {'f1-score': 0.8317460317460317,
       'precision': 0.8397435897435898,
       'recall': 0.8238993710691824,
       'support': 159},
 '4': {'f1-score': 0.8589473684210527,
       'precision': 0.7727272727272727,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7693817468105987,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 23
total_loss=109.9637474238053
counter=64
loss=total_loss/counter=1.7181835534969578
confusion_matrix=
[[160  39   2   2   2]
 [  1 106 113  26  24]
 [  0   3 124   1  46]
 [  0  18   0 141   0]
 [  0   0   6   2 203]]
classification_report=
{'0': {'f1-score': 0.8743169398907104,
       'precision': 0.9937888198757764,
       'recall': 0.7804878048780488,
       'support': 205},
 '1': {'f1-score': 0.4862385321100917,
       'precision': 0.6385542168674698,
       'recall': 0.3925925925925926,
       'support': 270},
 '2': {'f1-score': 0.5918854415274462,
       'precision': 0.5061224489795918,
       'recall': 0.7126436781609196,
       'support': 174},
 '3': {'f1-score': 0.851963746223565,
       'precision': 0.8197674418604651,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8353909465020576,
       'precision': 0.7381818181818182,
       'recall': 0.9620853080568721,
       'support': 211},
 'accuracy': 0.7203140333660452,
 'macro avg': {'f1-

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 24
total_loss=92.478475432077
counter=64
loss=total_loss/counter=1.4449761786262032
confusion_matrix=
[[182  20   1   1   1]
 [  7 129  94  31   9]
 [  0  10 119   4  41]
 [  1  19   0 139   0]
 [  0   1   7   3 200]]
classification_report=
{'0': {'f1-score': 0.9215189873417722,
       'precision': 0.9578947368421052,
       'recall': 0.8878048780487805,
       'support': 205},
 '1': {'f1-score': 0.5746102449888641,
       'precision': 0.7206703910614525,
       'recall': 0.4777777777777778,
       'support': 270},
 '2': {'f1-score': 0.6025316455696202,
       'precision': 0.5384615384615384,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8249258160237389,
       'precision': 0.7808988764044944,
       'recall': 0.8742138364779874,
       'support': 159},
 '4': {'f1-score': 0.8658008658008658,
       'precision': 0.796812749003984,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7546614327772326,
 'macro avg': {'f1-sc

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 25
total_loss=103.32513143914845
counter=64
loss=total_loss/counter=1.6144551787366945
confusion_matrix=
[[152  45   1   3   4]
 [  1 132  88  26  23]
 [  0   9 113   5  47]
 [  0  23   0 135   1]
 [  0   0   5   2 204]]
classification_report=
{'0': {'f1-score': 0.8491620111731844,
       'precision': 0.9934640522875817,
       'recall': 0.7414634146341463,
       'support': 205},
 '1': {'f1-score': 0.5511482254697285,
       'precision': 0.631578947368421,
       'recall': 0.4888888888888889,
       'support': 270},
 '2': {'f1-score': 0.5931758530183726,
       'precision': 0.5458937198067633,
       'recall': 0.6494252873563219,
       'support': 174},
 '3': {'f1-score': 0.8181818181818182,
       'precision': 0.7894736842105263,
       'recall': 0.8490566037735849,
       'support': 159},
 '4': {'f1-score': 0.8326530612244898,
       'precision': 0.7311827956989247,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7222767419038273,
 'macro avg': {'f1-

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 26
total_loss=105.61619185140394
counter=64
loss=total_loss/counter=1.6502529976781866
confusion_matrix=
[[175  25   1   3   1]
 [  1 114  99  39  17]
 [  0   5 117   5  47]
 [  0  15   0 143   1]
 [  0   0   6   3 202]]
classification_report=
{'0': {'f1-score': 0.9186351706036745,
       'precision': 0.9943181818181818,
       'recall': 0.8536585365853658,
       'support': 205},
 '1': {'f1-score': 0.5314685314685315,
       'precision': 0.7169811320754716,
       'recall': 0.4222222222222222,
       'support': 270},
 '2': {'f1-score': 0.5894206549118387,
       'precision': 0.5246636771300448,
       'recall': 0.6724137931034483,
       'support': 174},
 '3': {'f1-score': 0.8125,
       'precision': 0.7409326424870466,
       'recall': 0.89937106918239,
       'support': 159},
 '4': {'f1-score': 0.8434237995824635,
       'precision': 0.753731343283582,
       'recall': 0.957345971563981,
       'support': 211},
 'accuracy': 0.7369970559371933,
 'macro avg': {'f1-score': 0.7390

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 27
total_loss=109.0142358252304
counter=64
loss=total_loss/counter=1.703347434769225
confusion_matrix=
[[170  30   1   2   2]
 [  0 112 110  32  16]
 [  0   6 121   3  44]
 [  0  18   0 140   1]
 [  0   0   8   3 200]]
classification_report=
{'0': {'f1-score': 0.9066666666666667,
       'precision': 1.0,
       'recall': 0.8292682926829268,
       'support': 205},
 '1': {'f1-score': 0.5137614678899083,
       'precision': 0.6746987951807228,
       'recall': 0.4148148148148148,
       'support': 270},
 '2': {'f1-score': 0.5845410628019323,
       'precision': 0.5041666666666667,
       'recall': 0.6954022988505747,
       'support': 174},
 '3': {'f1-score': 0.8259587020648967,
       'precision': 0.7777777777777778,
       'recall': 0.8805031446540881,
       'support': 159},
 '4': {'f1-score': 0.8438818565400844,
       'precision': 0.7604562737642585,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7291462217860648,
 'macro avg': {'f1-score': 0.73496

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 28
total_loss=113.57340344106409
counter=64
loss=total_loss/counter=1.7745844287666264
confusion_matrix=
[[167  33   1   2   2]
 [  0 114 109  25  22]
 [  0   7 117   3  47]
 [  0  20   0 138   1]
 [  0   0   5   1 205]]
classification_report=
{'0': {'f1-score': 0.8978494623655914,
       'precision': 1.0,
       'recall': 0.8146341463414634,
       'support': 205},
 '1': {'f1-score': 0.5135135135135135,
       'precision': 0.6551724137931034,
       'recall': 0.4222222222222222,
       'support': 270},
 '2': {'f1-score': 0.5763546798029556,
       'precision': 0.5043103448275862,
       'recall': 0.6724137931034483,
       'support': 174},
 '3': {'f1-score': 0.8414634146341463,
       'precision': 0.8165680473372781,
       'recall': 0.8679245283018868,
       'support': 159},
 '4': {'f1-score': 0.8401639344262296,
       'precision': 0.740072202166065,
       'recall': 0.9715639810426541,
       'support': 211},
 'accuracy': 0.7271835132482827,
 'macro avg': {'f1-score': 0.7338

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 29
total_loss=99.5237001264658
counter=64
loss=total_loss/counter=1.555057814476028
confusion_matrix=
[[178  24   1   1   1]
 [  4 128 101  25  12]
 [  0   9 120   3  42]
 [  0  21   0 137   1]
 [  0   2   8   2 199]]
classification_report=
{'0': {'f1-score': 0.9198966408268734,
       'precision': 0.978021978021978,
       'recall': 0.8682926829268293,
       'support': 205},
 '1': {'f1-score': 0.5638766519823789,
       'precision': 0.6956521739130435,
       'recall': 0.4740740740740741,
       'support': 270},
 '2': {'f1-score': 0.594059405940594,
       'precision': 0.5217391304347826,
       'recall': 0.6896551724137931,
       'support': 174},
 '3': {'f1-score': 0.8379204892966361,
       'precision': 0.8154761904761905,
       'recall': 0.8616352201257862,
       'support': 159},
 '4': {'f1-score': 0.8540772532188842,
       'precision': 0.7803921568627451,
       'recall': 0.943127962085308,
       'support': 211},
 'accuracy': 0.7477919528949951,
 'macro avg': {'f1-scor

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 30
total_loss=108.85232330071432
counter=64
loss=total_loss/counter=1.7008175515736612
confusion_matrix=
[[180  20   1   2   2]
 [  3 116 103  26  22]
 [  0   6 118   3  47]
 [  0  20   0 138   1]
 [  0   0   6   1 204]]
classification_report=
{'0': {'f1-score': 0.9278350515463918,
       'precision': 0.9836065573770492,
       'recall': 0.8780487804878049,
       'support': 205},
 '1': {'f1-score': 0.5370370370370371,
       'precision': 0.7160493827160493,
       'recall': 0.42962962962962964,
       'support': 270},
 '2': {'f1-score': 0.5870646766169154,
       'precision': 0.5175438596491229,
       'recall': 0.6781609195402298,
       'support': 174},
 '3': {'f1-score': 0.8389057750759878,
       'precision': 0.8117647058823529,
       'recall': 0.8679245283018868,
       'support': 159},
 '4': {'f1-score': 0.837782340862423,
       'precision': 0.7391304347826086,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7419038272816487,
 'macro avg': {'f1

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 31
total_loss=114.39757604912583
counter=64
loss=total_loss/counter=1.7874621257675911
confusion_matrix=
[[169  31   1   2   2]
 [  1 117  99  30  23]
 [  0   7 117   3  47]
 [  0  18   0 140   1]
 [  0   0   5   1 205]]
classification_report=
{'0': {'f1-score': 0.9013333333333333,
       'precision': 0.9941176470588236,
       'recall': 0.824390243902439,
       'support': 205},
 '1': {'f1-score': 0.5282167042889392,
       'precision': 0.6763005780346821,
       'recall': 0.43333333333333335,
       'support': 270},
 '2': {'f1-score': 0.5909090909090909,
       'precision': 0.527027027027027,
       'recall': 0.6724137931034483,
       'support': 174},
 '3': {'f1-score': 0.835820895522388,
       'precision': 0.7954545454545454,
       'recall': 0.8805031446540881,
       'support': 159},
 '4': {'f1-score': 0.8384458077709612,
       'precision': 0.737410071942446,
       'recall': 0.9715639810426541,
       'support': 211},
 'accuracy': 0.7340529931305201,
 'macro avg': {'f1-s

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 32
total_loss=109.32749863478271
counter=64
loss=total_loss/counter=1.70824216616848
confusion_matrix=
[[175  27   1   0   2]
 [  2 128  97  24  19]
 [  0   9 116   3  46]
 [  0  25   0 133   1]
 [  0   0   7   1 203]]
classification_report=
{'0': {'f1-score': 0.9162303664921466,
       'precision': 0.9887005649717514,
       'recall': 0.8536585365853658,
       'support': 205},
 '1': {'f1-score': 0.5577342047930283,
       'precision': 0.6772486772486772,
       'recall': 0.4740740740740741,
       'support': 270},
 '2': {'f1-score': 0.5873417721518988,
       'precision': 0.5248868778280543,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8312499999999999,
       'precision': 0.8260869565217391,
       'recall': 0.8364779874213837,
       'support': 159},
 '4': {'f1-score': 0.8423236514522822,
       'precision': 0.7490774907749077,
       'recall': 0.9620853080568721,
       'support': 211},
 'accuracy': 0.7409224730127576,
 'macro avg': {'f1-

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 33
total_loss=120.16536936537159
counter=64
loss=total_loss/counter=1.877583896333931
confusion_matrix=
[[174  26   2   1   2]
 [  1 110 112  26  21]
 [  0   7 121   2  44]
 [  0  22   0 136   1]
 [  0   0   7   1 203]]
classification_report=
{'0': {'f1-score': 0.9157894736842105,
       'precision': 0.9942857142857143,
       'recall': 0.848780487804878,
       'support': 205},
 '1': {'f1-score': 0.5057471264367817,
       'precision': 0.6666666666666666,
       'recall': 0.4074074074074074,
       'support': 270},
 '2': {'f1-score': 0.5817307692307693,
       'precision': 0.5,
       'recall': 0.6954022988505747,
       'support': 174},
 '3': {'f1-score': 0.8369230769230769,
       'precision': 0.8192771084337349,
       'recall': 0.8553459119496856,
       'support': 159},
 '4': {'f1-score': 0.8423236514522822,
       'precision': 0.7490774907749077,
       'recall': 0.9620853080568721,
       'support': 211},
 'accuracy': 0.7301275760549558,
 'macro avg': {'f1-score': 0.73650

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 34
total_loss=106.0776572126625
counter=64
loss=total_loss/counter=1.6574633939478516
confusion_matrix=
[[165  36   1   3   0]
 [  2 144  89  25  10]
 [  0  12 115   4  43]
 [  0  27   0 131   1]
 [  0   1   7   2 201]]
classification_report=
{'0': {'f1-score': 0.8870967741935485,
       'precision': 0.9880239520958084,
       'recall': 0.8048780487804879,
       'support': 205},
 '1': {'f1-score': 0.5877551020408163,
       'precision': 0.6545454545454545,
       'recall': 0.5333333333333333,
       'support': 270},
 '2': {'f1-score': 0.5958549222797928,
       'precision': 0.5424528301886793,
       'recall': 0.6609195402298851,
       'support': 174},
 '3': {'f1-score': 0.808641975308642,
       'precision': 0.793939393939394,
       'recall': 0.8238993710691824,
       'support': 159},
 '4': {'f1-score': 0.8626609442060086,
       'precision': 0.788235294117647,
       'recall': 0.95260663507109,
       'support': 211},
 'accuracy': 0.7419038272816487,
 'macro avg': {'f1-scor

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 35
total_loss=111.82023716508552
counter=64
loss=total_loss/counter=1.7471912057044612
confusion_matrix=
[[181  18   1   4   1]
 [  2 104 114  34  16]
 [  0   5 122   5  42]
 [  0  17   0 141   1]
 [  0   0   8   2 201]]
classification_report=
{'0': {'f1-score': 0.9329896907216495,
       'precision': 0.9890710382513661,
       'recall': 0.8829268292682927,
       'support': 205},
 '1': {'f1-score': 0.5024154589371981,
       'precision': 0.7222222222222222,
       'recall': 0.3851851851851852,
       'support': 270},
 '2': {'f1-score': 0.5823389021479713,
       'precision': 0.49795918367346936,
       'recall': 0.7011494252873564,
       'support': 174},
 '3': {'f1-score': 0.8173913043478261,
       'precision': 0.7580645161290323,
       'recall': 0.8867924528301887,
       'support': 159},
 '4': {'f1-score': 0.8516949152542371,
       'precision': 0.7701149425287356,
       'recall': 0.95260663507109,
       'support': 211},
 'accuracy': 0.7350343473994112,
 'macro avg': {'f1

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 36
total_loss=108.49152852401602
counter=64
loss=total_loss/counter=1.6951801331877503
confusion_matrix=
[[155  41   0   7   2]
 [  5 129  69  41  26]
 [  0   8 104   6  56]
 [  0  14   0 144   1]
 [  0   0   2   3 206]]
classification_report=
{'0': {'f1-score': 0.8493150684931506,
       'precision': 0.96875,
       'recall': 0.7560975609756098,
       'support': 205},
 '1': {'f1-score': 0.5584415584415584,
       'precision': 0.671875,
       'recall': 0.4777777777777778,
       'support': 270},
 '2': {'f1-score': 0.5959885386819483,
       'precision': 0.5942857142857143,
       'recall': 0.5977011494252874,
       'support': 174},
 '3': {'f1-score': 0.7999999999999999,
       'precision': 0.7164179104477612,
       'recall': 0.9056603773584906,
       'support': 159},
 '4': {'f1-score': 0.8207171314741036,
       'precision': 0.7079037800687286,
       'recall': 0.976303317535545,
       'support': 211},
 'accuracy': 0.7242394504416094,
 'macro avg': {'f1-score': 0.7248924594

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 37
total_loss=103.09163476246671
counter=64
loss=total_loss/counter=1.6108067931635424
confusion_matrix=
[[169  27   1   7   1]
 [  2 130  87  35  16]
 [  0  10 118   4  42]
 [  0  14   0 144   1]
 [  0   1   7   3 200]]
classification_report=
{'0': {'f1-score': 0.898936170212766,
       'precision': 0.9883040935672515,
       'recall': 0.824390243902439,
       'support': 205},
 '1': {'f1-score': 0.575221238938053,
       'precision': 0.7142857142857143,
       'recall': 0.48148148148148145,
       'support': 270},
 '2': {'f1-score': 0.6098191214470284,
       'precision': 0.5539906103286385,
       'recall': 0.6781609195402298,
       'support': 174},
 '3': {'f1-score': 0.8181818181818182,
       'precision': 0.7461139896373057,
       'recall': 0.9056603773584906,
       'support': 159},
 '4': {'f1-score': 0.8492569002123144,
       'precision': 0.7692307692307693,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.746810598626104,
 'macro avg': {'f1-s

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 38
total_loss=105.58325290832668
counter=64
loss=total_loss/counter=1.6497383266926045
confusion_matrix=
[[180  19   1   1   4]
 [  2 115 106  30  17]
 [  0   4 123   1  46]
 [  0  30   2 126   1]
 [  0   0   8   1 202]]
classification_report=
{'0': {'f1-score': 0.930232558139535,
       'precision': 0.989010989010989,
       'recall': 0.8780487804878049,
       'support': 205},
 '1': {'f1-score': 0.5251141552511416,
       'precision': 0.6845238095238095,
       'recall': 0.42592592592592593,
       'support': 270},
 '2': {'f1-score': 0.5942028985507246,
       'precision': 0.5125,
       'recall': 0.7068965517241379,
       'support': 174},
 '3': {'f1-score': 0.7924528301886793,
       'precision': 0.7924528301886793,
       'recall': 0.7924528301886793,
       'support': 159},
 '4': {'f1-score': 0.8399168399168399,
       'precision': 0.7481481481481481,
       'recall': 0.957345971563981,
       'support': 211},
 'accuracy': 0.732090284592738,
 'macro avg': {'f1-score': 0.736

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 39
total_loss=112.99608951653482
counter=64
loss=total_loss/counter=1.7655638986958566
confusion_matrix=
[[183  17   1   2   2]
 [  2 117 113  18  20]
 [  1   5 121   1  46]
 [  1  34   0 123   1]
 [  0   1   5   1 204]]
classification_report=
{'0': {'f1-score': 0.9336734693877552,
       'precision': 0.9786096256684492,
       'recall': 0.8926829268292683,
       'support': 205},
 '1': {'f1-score': 0.5270270270270271,
       'precision': 0.6724137931034483,
       'recall': 0.43333333333333335,
       'support': 270},
 '2': {'f1-score': 0.5845410628019323,
       'precision': 0.5041666666666667,
       'recall': 0.6954022988505747,
       'support': 174},
 '3': {'f1-score': 0.8092105263157894,
       'precision': 0.8482758620689655,
       'recall': 0.7735849056603774,
       'support': 159},
 '4': {'f1-score': 0.8429752066115703,
       'precision': 0.7472527472527473,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7340529931305201,
 'macro avg': {'f

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 40
total_loss=117.4059408735708
counter=64
loss=total_loss/counter=1.8344678261495437
confusion_matrix=
[[161  38   1   3   2]
 [  1 126 106  20  17]
 [  0   7 119   2  46]
 [  0  24   0 134   1]
 [  0   1   5   1 204]]
classification_report=
{'0': {'f1-score': 0.8773841961852861,
       'precision': 0.9938271604938271,
       'recall': 0.7853658536585366,
       'support': 205},
 '1': {'f1-score': 0.5407725321888412,
       'precision': 0.6428571428571429,
       'recall': 0.4666666666666667,
       'support': 270},
 '2': {'f1-score': 0.5876543209876544,
       'precision': 0.5151515151515151,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8401253918495297,
       'precision': 0.8375,
       'recall': 0.8427672955974843,
       'support': 159},
 '4': {'f1-score': 0.8482328482328482,
       'precision': 0.7555555555555555,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7301275760549558,
 'macro avg': {'f1-score': 0.73

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 41
total_loss=110.52458054800768
counter=64
loss=total_loss/counter=1.72694657106262
confusion_matrix=
[[182  18   1   2   2]
 [  4 130 102  18  16]
 [  1   9 119   0  45]
 [  1  36   1 120   1]
 [  0   1   5   1 204]]
classification_report=
{'0': {'f1-score': 0.9262086513994912,
       'precision': 0.9680851063829787,
       'recall': 0.8878048780487805,
       'support': 205},
 '1': {'f1-score': 0.5603448275862069,
       'precision': 0.6701030927835051,
       'recall': 0.48148148148148145,
       'support': 270},
 '2': {'f1-score': 0.5920398009950248,
       'precision': 0.5219298245614035,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8,
       'precision': 0.851063829787234,
       'recall': 0.7547169811320755,
       'support': 159},
 '4': {'f1-score': 0.8517745302713987,
       'precision': 0.7611940298507462,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7409224730127576,
 'macro avg': {'f1-score': 0.746073

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 42
total_loss=114.79330780008034
counter=64
loss=total_loss/counter=1.7936454343762553
confusion_matrix=
[[179  20   1   3   2]
 [  3 128 101  22  16]
 [  1   8 119   1  45]
 [  0  28   0 130   1]
 [  0   1   5   1 204]]
classification_report=
{'0': {'f1-score': 0.9226804123711341,
       'precision': 0.9781420765027322,
       'recall': 0.8731707317073171,
       'support': 205},
 '1': {'f1-score': 0.5626373626373627,
       'precision': 0.6918918918918919,
       'recall': 0.4740740740740741,
       'support': 270},
 '2': {'f1-score': 0.595,
       'precision': 0.5265486725663717,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8227848101265823,
       'precision': 0.8280254777070064,
       'recall': 0.8176100628930818,
       'support': 159},
 '4': {'f1-score': 0.8517745302713987,
       'precision': 0.7611940298507462,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.745829244357213,
 'macro avg': {'f1-score': 0.750

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 43
total_loss=121.48909921601643
counter=64
loss=total_loss/counter=1.8982671752502567
confusion_matrix=
[[159  39   1   5   1]
 [  0 128  98  29  15]
 [  0   9 116   4  45]
 [  0  23   0 135   1]
 [  0   2   3   1 205]]
classification_report=
{'0': {'f1-score': 0.8736263736263736,
       'precision': 1.0,
       'recall': 0.775609756097561,
       'support': 205},
 '1': {'f1-score': 0.5435244161358811,
       'precision': 0.6368159203980099,
       'recall': 0.4740740740740741,
       'support': 270},
 '2': {'f1-score': 0.5918367346938775,
       'precision': 0.5321100917431193,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8108108108108107,
       'precision': 0.7758620689655172,
       'recall': 0.8490566037735849,
       'support': 159},
 '4': {'f1-score': 0.8577405857740585,
       'precision': 0.7677902621722846,
       'recall': 0.9715639810426541,
       'support': 211},
 'accuracy': 0.7291462217860648,
 'macro avg': {'f1-score': 0.7355

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 44
total_loss=123.94166429647413
counter=64
loss=total_loss/counter=1.9365885046324083
confusion_matrix=
[[158  40   1   5   1]
 [  1 127  98  29  15]
 [  0   9 116   4  45]
 [  0  24   0 134   1]
 [  0   2   4   1 204]]
classification_report=
{'0': {'f1-score': 0.8681318681318682,
       'precision': 0.9937106918238994,
       'recall': 0.7707317073170732,
       'support': 205},
 '1': {'f1-score': 0.538135593220339,
       'precision': 0.6287128712871287,
       'recall': 0.4703703703703704,
       'support': 270},
 '2': {'f1-score': 0.5903307888040712,
       'precision': 0.5296803652968036,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.8072289156626506,
       'precision': 0.7745664739884393,
       'recall': 0.8427672955974843,
       'support': 159},
 '4': {'f1-score': 0.8553459119496855,
       'precision': 0.7669172932330827,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7252208047105005,
 'macro avg': {'f1-

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 45
total_loss=125.24112888562104
counter=64
loss=total_loss/counter=1.9568926388378287
confusion_matrix=
[[162  36   1   4   2]
 [  1 127 103  23  16]
 [  0   8 119   2  45]
 [  0  28   0 130   1]
 [  0   2   3   1 205]]
classification_report=
{'0': {'f1-score': 0.8804347826086958,
       'precision': 0.9938650306748467,
       'recall': 0.7902439024390244,
       'support': 205},
 '1': {'f1-score': 0.5392781316348195,
       'precision': 0.6318407960199005,
       'recall': 0.4703703703703704,
       'support': 270},
 '2': {'f1-score': 0.595,
       'precision': 0.5265486725663717,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8150470219435737,
       'precision': 0.8125,
       'recall': 0.8176100628930818,
       'support': 159},
 '4': {'f1-score': 0.8541666666666667,
       'precision': 0.7620817843866171,
       'recall': 0.9715639810426541,
       'support': 211},
 'accuracy': 0.7291462217860648,
 'macro avg': {'f1-score': 0.7367853205707

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 46
total_loss=116.87233616150867
counter=64
loss=total_loss/counter=1.826130252523573
confusion_matrix=
[[166  33   3   2   1]
 [  1 125 115  20   9]
 [  0   8 129   0  37]
 [  0  33   0 125   1]
 [  0   2   8   1 200]]
classification_report=
{'0': {'f1-score': 0.8924731182795699,
       'precision': 0.9940119760479041,
       'recall': 0.8097560975609757,
       'support': 205},
 '1': {'f1-score': 0.5307855626326963,
       'precision': 0.6218905472636815,
       'recall': 0.46296296296296297,
       'support': 270},
 '2': {'f1-score': 0.6013986013986014,
       'precision': 0.5058823529411764,
       'recall': 0.7413793103448276,
       'support': 174},
 '3': {'f1-score': 0.8143322475570033,
       'precision': 0.8445945945945946,
       'recall': 0.7861635220125787,
       'support': 159},
 '4': {'f1-score': 0.8714596949891067,
       'precision': 0.8064516129032258,
       'recall': 0.9478672985781991,
       'support': 211},
 'accuracy': 0.7311089303238469,
 'macro avg': {'f

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 47
total_loss=115.10689880164318
counter=64
loss=total_loss/counter=1.7985452937756747
confusion_matrix=
[[170  31   0   2   2]
 [  1 148  81  26  14]
 [  0  15 111   3  45]
 [  0  37   0 121   1]
 [  0   2   4   1 204]]
classification_report=
{'0': {'f1-score': 0.9042553191489361,
       'precision': 0.9941520467836257,
       'recall': 0.8292682926829268,
       'support': 205},
 '1': {'f1-score': 0.588469184890656,
       'precision': 0.6351931330472103,
       'recall': 0.5481481481481482,
       'support': 270},
 '2': {'f1-score': 0.6,
       'precision': 0.5663265306122449,
       'recall': 0.6379310344827587,
       'support': 174},
 '3': {'f1-score': 0.7756410256410258,
       'precision': 0.7908496732026143,
       'recall': 0.7610062893081762,
       'support': 159},
 '4': {'f1-score': 0.8553459119496855,
       'precision': 0.7669172932330827,
       'recall': 0.966824644549763,
       'support': 211},
 'accuracy': 0.7399411187438666,
 'macro avg': {'f1-score': 0.74474

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 48
total_loss=117.56322756165827
counter=64
loss=total_loss/counter=1.8369254306509104
confusion_matrix=
[[159  41   1   4   0]
 [  0 134  94  33   9]
 [  0  13 116   6  39]
 [  0  24   0 135   0]
 [  0   3   8   2 198]]
classification_report=
{'0': {'f1-score': 0.8736263736263736,
       'precision': 1.0,
       'recall': 0.775609756097561,
       'support': 205},
 '1': {'f1-score': 0.5525773195876289,
       'precision': 0.6232558139534884,
       'recall': 0.4962962962962963,
       'support': 270},
 '2': {'f1-score': 0.5903307888040712,
       'precision': 0.5296803652968036,
       'recall': 0.6666666666666666,
       'support': 174},
 '3': {'f1-score': 0.7964601769911505,
       'precision': 0.75,
       'recall': 0.8490566037735849,
       'support': 159},
 '4': {'f1-score': 0.8665207877461708,
       'precision': 0.8048780487804879,
       'recall': 0.9383886255924171,
       'support': 211},
 'accuracy': 0.7281648675171737,
 'macro avg': {'f1-score': 0.735903089351079,
 

/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py:1134: UserWarning: The inner type of a container is lost when calling torch.jit.isinstance in eager mode. For example, List[int] would become list and therefore falsely return True for List[float] or List[str].
  warnings.warn("The inner type of a container is lost when "


EPOCH 49
total_loss=128.34153404941736
counter=64
loss=total_loss/counter=2.0053364695221463
confusion_matrix=
[[172  28   1   2   2]
 [  1 114 113  28  14]
 [  0   8 119   5  42]
 [  0  22   0 136   1]
 [  0   2   7   1 201]]
classification_report=
{'0': {'f1-score': 0.9100529100529099,
       'precision': 0.9942196531791907,
       'recall': 0.8390243902439024,
       'support': 205},
 '1': {'f1-score': 0.5135135135135135,
       'precision': 0.6551724137931034,
       'recall': 0.4222222222222222,
       'support': 270},
 '2': {'f1-score': 0.5748792270531401,
       'precision': 0.49583333333333335,
       'recall': 0.6839080459770115,
       'support': 174},
 '3': {'f1-score': 0.8217522658610273,
       'precision': 0.7906976744186046,
       'recall': 0.8553459119496856,
       'support': 159},
 '4': {'f1-score': 0.8535031847133757,
       'precision': 0.7730769230769231,
       'recall': 0.95260663507109,
       'support': 211},
 'accuracy': 0.7281648675171737,
 'macro avg': {'f1